export const MENU_SIDE_OPTION = 'MENU_SIDE_OPTION';
export const HANDLER_ALERT_MODAL = 'HANDLER_ALERT_MODAL';
export const CLOSE_ALERT_MODAL = 'CLOSE_ALERT_MODAL';


export const SUBJECT_GET_REQUESTING = "SUBJECT_GET_REQUESTING";
export const SUBJECT_GET_SUCCESS = "SUBJECT_GET_SUCCESS";
export const SUBJECT_GET_ERROR = "SUBJECT_GET_ERROR";



