export const MENU_SIDE_OPTION = 'MENU_SIDE_OPTION';
export const HANDLER_ALERT_MODAL = 'HANDLER_ALERT_MODAL';
export const CLOSE_ALERT_MODAL = 'CLOSE_ALERT_MODAL';


export const SUBJECT_GET_REQUESTING = "SUBJECT_GET_REQUESTING";
export const SUBJECT_GET_SUCCESS = "SUBJECT_GET_SUCCESS";
export const SUBJECT_GET_ERROR = "SUBJECT_GET_ERROR";


export const USERS_GET_REQUESTING = "USERS_GET_REQUESTING";
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS";
export const USERS_GET_ERROR = "USERS_GET_ERROR";

export const USERS_DELETE_REQUESTING = "USERS_DELETE_REQUESTING";
export const USERS_DELETE_SUCCESS = "USERS_DELETE_SUCCESS";
export const USERS_DELETE_ERROR = "USERS_DELETE_ERROR";

export const CHANGE_CREATE_USER_FORM = "CHANGE_CREATE_USER_FORM";

export const RESETSTATE = "RESETSTATE";

export const CREATE_USER_REQUESTING = "CREATE_USER_REQUESTING";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

